### ISSUE TITLE
Change base url

### ISSUE THREAD

**Issue by J22Pregbaha** [inveniosoftware/flask-sitemap#47]
First off, thank you very much for this package. You have done something truly wonderful here.

I'm always frustrated when I can't change the base URL to what I want. For example, all the location URLs are created on localhost:5000 when the flask app runs on port 5000 on my localhost. I would like to be able to change that URL to what I want it to be.

**Comment by lnielsen** [comment]
Hi 👋

Flask-Sitemap is using the [``url_for``](https://flask.palletsprojects.com/en/2.0.x/api/#flask.url_for) from Flask to generate the URL. Thus in order to change the base URL you should set ``SERVER_NAME`` configuration variable (by default ``url_for`` relies on the ``Host`` HTTP header.


Does this answer your question?
